#include "../include/codegen.hpp"
#include <fstream>
#include <iostream>

CodeGen::CodeGen(const std::string& cpp_code) : cpp_code(cpp_code) {}

void CodeGen::generateCPlusPlus(const std::string& output_filename) {
    std::ofstream out(output_filename);
    if (!out.is_open()) {
        std::cerr << "Error: Cannot write to " << output_filename << "\n";
        return;
    }

    out << "#include <iostream>\n";
    out << "#include <string>\n";
    out << "#include <tuple>\n";
    out << "#include <fstream>\n";
    out << "#include <sstream>\n\n";
    out << "#include <cstdlib>\n\n";
    out << "#include <vector>\n";
    out << "#include <map>\n";
    out << "#include <variant>\n";
    out << "#include <memory>\n";
    out << "#include <gc.h>\n\n"; // Include Boehm GC
    out << "#include <cstdint>\n\n";
    out << "#include <cmath>\n\n";
    out << "#include <type_traits>\n\n";
    out << "#include <algorithm>\n\n";
    out << "#include <chrono>\n";
    out << "#include <thread>\n";
    out << "#include <regex>\n\n";
    
    // np_string wrapper to add .slice() to standard strings
    out << "struct np_var;\n";
    out << "struct np_string : public std::string {\n";
    out << "    using std::string::string;\n";
    out << "    np_string() : std::string() {}\n";
    out << "    np_string(const std::string& s) : std::string(s) {}\n";
    out << "    np_string(const char* s) : std::string(s) {}\n";
    out << "    np_string slice(int start, int end) const {\n";
    out << "        int len = this->length();\n";
    out << "        if (end == -999999) end = len;\n";
    out << "        if (start < 0) start += len; if (start < 0) start = 0; if (start > len) start = len;\n";
    out << "        if (end < 0) end += len; if (end < 0) end = 0; if (end > len) end = len;\n";
    out << "        if (end < start) end = start;\n";
    out << "        return this->substr(start, end - start);\n";
    out << "    }\n";
    out << "    np_var split(const std::string& delim) const;\n";
    out << "    np_string join(const np_var& arr) const;\n";
    out << "    np_string trim() const;\n";
    out << "};\n\n";

    out << "inline np_string operator+(const np_string& lhs, const np_string& rhs) { return np_string(static_cast<const std::string&>(lhs) + static_cast<const std::string&>(rhs)); }\n";
    out << "inline np_string operator+(const np_string& lhs, const char* rhs) { return np_string(static_cast<const std::string&>(lhs) + rhs); }\n";
    out << "inline np_string operator+(const char* lhs, const np_string& rhs) { return np_string(lhs + static_cast<const std::string&>(rhs)); }\n";
    out << "inline np_string operator+(const np_string& lhs, const std::string& rhs) { return np_string(static_cast<const std::string&>(lhs) + rhs); }\n";
    out << "inline np_string operator+(const std::string& lhs, const np_string& rhs) { return np_string(lhs + static_cast<const std::string&>(rhs)); }\n\n";

    out << "int np_throw_error(const std::string& msg) { std::cerr << msg << std::endl; std::exit(1); return 0; }\n\n";

    out << "#define NP_INT_PRIMITIVE_OPS(SelfType, PrimType) \\\n";
    out << "    friend SelfType operator+(SelfType a, PrimType b) { return a + SelfType(b); } \\\n";
    out << "    friend SelfType operator+(PrimType a, SelfType b) { return SelfType(a) + b; } \\\n";
    out << "    friend SelfType operator-(SelfType a, PrimType b) { return a - SelfType(b); } \\\n";
    out << "    friend SelfType operator-(PrimType a, SelfType b) { return SelfType(a) - b; } \\\n";
    out << "    friend SelfType operator*(SelfType a, PrimType b) { return a * SelfType(b); } \\\n";
    out << "    friend SelfType operator*(PrimType a, SelfType b) { return SelfType(a) * b; } \\\n";
    out << "    friend SelfType operator/(SelfType a, PrimType b) { return a / SelfType(b); } \\\n";
    out << "    friend SelfType operator/(PrimType a, SelfType b) { return SelfType(a) / b; } \\\n";
    out << "    friend SelfType operator%(SelfType a, PrimType b) { return a % SelfType(b); } \\\n";
    out << "    friend SelfType operator%(PrimType a, SelfType b) { return SelfType(a) % b; } \\\n";
    out << "    friend bool operator>(SelfType a, PrimType b) { return a > SelfType(b); } \\\n";
    out << "    friend bool operator>(PrimType a, SelfType b) { return SelfType(a) > b; } \\\n";
    out << "    friend bool operator<(SelfType a, PrimType b) { return a < SelfType(b); } \\\n";
    out << "    friend bool operator<(PrimType a, SelfType b) { return SelfType(a) < b; } \\\n";
    out << "    friend bool operator>=(SelfType a, PrimType b) { return a >= SelfType(b); } \\\n";
    out << "    friend bool operator>=(PrimType a, SelfType b) { return SelfType(a) >= b; } \\\n";
    out << "    friend bool operator<=(SelfType a, PrimType b) { return a <= SelfType(b); } \\\n";
    out << "    friend bool operator<=(PrimType a, SelfType b) { return SelfType(a) <= b; } \\\n";
    out << "    friend bool operator==(SelfType a, PrimType b) { return a == SelfType(b); } \\\n";
    out << "    friend bool operator==(PrimType a, SelfType b) { return SelfType(a) == b; } \\\n";
    out << "    friend bool operator!=(SelfType a, PrimType b) { return a != SelfType(b); } \\\n";
    out << "    friend bool operator!=(PrimType a, SelfType b) { return SelfType(a) != b; }\n\n";

    out << "struct np_int128 {\n";
    out << "    __int128 val;\n";
    out << "    np_int128() : val(0) {}\n";
    out << "    np_int128(__int128 v) : val(v) {}\n";
    out << "    np_int128(const char* str) {\n";
    out << "        val = 0;\n";
    out << "        bool neg = false;\n";
    out << "        if (*str == '-') { neg = true; str++; }\n";
    out << "        while (*str) {\n";
    out << "            if (*str >= '0' && *str <= '9') {\n";
    out << "                val = val * 10 + (*str - '0');\n";
    out << "            }\n";
    out << "            str++;\n";
    out << "        }\n";
    out << "        if (neg) val = -val;\n";
    out << "    }\n";
    out << "    std::string to_string() const {\n";
    out << "        if (val == 0) return \"0\";\n";
    out << "        std::string s = \"\";\n";
    out << "        __int128 temp = val;\n";
    out << "        bool neg = false;\n";
    out << "        if (temp < 0) { neg = true; temp = -temp; }\n";
    out << "        while (temp > 0) {\n";
    out << "            s += (char)('0' + (temp % 10));\n";
    out << "            temp /= 10;\n";
    out << "        }\n";
    out << "        if (neg) s += \"-\";\n";
    out << "        std::reverse(s.begin(), s.end());\n";
    out << "        return s;\n";
    out << "    }\n";
    out << "    operator double() const { return (double)val; }\n";
    out << "    operator int64_t() const { return (int64_t)val; }\n";
    out << "    operator __int128() const { return val; }\n";
    out << "    friend std::ostream& operator<<(std::ostream& os, const np_int128& val) { os << val.to_string(); return os; }\n";
    out << "    friend np_int128 operator+(np_int128 a, np_int128 b) { return a.val + b.val; }\n";
    out << "    friend np_int128 operator-(np_int128 a, np_int128 b) { return a.val - b.val; }\n";
    out << "    friend np_int128 operator*(np_int128 a, np_int128 b) { return a.val * b.val; }\n";
    out << "    friend np_int128 operator/(np_int128 a, np_int128 b) { return a.val / b.val; }\n";
    out << "    friend np_int128 operator%(np_int128 a, np_int128 b) { return a.val % b.val; }\n";
    out << "    friend bool operator>(np_int128 a, np_int128 b) { return a.val > b.val; }\n";
    out << "    friend bool operator<(np_int128 a, np_int128 b) { return a.val < b.val; }\n";
    out << "    friend bool operator>=(np_int128 a, np_int128 b) { return a.val >= b.val; }\n";
    out << "    friend bool operator<=(np_int128 a, np_int128 b) { return a.val <= b.val; }\n";
    out << "    friend bool operator==(np_int128 a, np_int128 b) { return a.val == b.val; }\n";
    out << "    friend bool operator!=(np_int128 a, np_int128 b) { return a.val != b.val; }\n";
    out << "    NP_INT_PRIMITIVE_OPS(np_int128, int)\n";
    out << "    NP_INT_PRIMITIVE_OPS(np_int128, int64_t)\n";
    out << "};\n\n";

    out << "struct np_int256 {\n";
    out << "    unsigned __int128 low;\n";
    out << "    __int128 high;\n";
    out << "    np_int256() : low(0), high(0) {}\n";
    out << "    np_int256(__int128 v) : low(v), high(v < 0 ? -1 : 0) {}\n";
    out << "    np_int256(unsigned __int128 l, __int128 h) : low(l), high(h) {}\n";
    out << "    np_int256(const char* str) {\n";
    out << "        low = 0; high = 0;\n";
    out << "        bool neg = false;\n";
    out << "        if (*str == '-') { neg = true; str++; }\n";
    out << "        while (*str) {\n";
    out << "            if (*str >= '0' && *str <= '9') {\n";
    out << "                *this = *this * 10 + np_int256(static_cast<__int128>(*str - '0'));\n";
    out << "            }\n";
    out << "            str++;\n";
    out << "        }\n";
    out << "        if (neg) *this = np_int256() - *this;\n";
    out << "    }\n";
    out << "    unsigned int divmod10() {\n";
    out << "        unsigned int words[8];\n";
    out << "        words[0] = (unsigned int)(low & 0xFFFFFFFF);\n";
    out << "        words[1] = (unsigned int)((low >> 32) & 0xFFFFFFFF);\n";
    out << "        words[2] = (unsigned int)((low >> 64) & 0xFFFFFFFF);\n";
    out << "        words[3] = (unsigned int)((low >> 96) & 0xFFFFFFFF);\n";
    out << "        words[4] = (unsigned int)(high & 0xFFFFFFFF);\n";
    out << "        words[5] = (unsigned int)((high >> 32) & 0xFFFFFFFF);\n";
    out << "        words[6] = (unsigned int)((high >> 64) & 0xFFFFFFFF);\n";
    out << "        words[7] = (unsigned int)((high >> 96) & 0xFFFFFFFF);\n";
    out << "        unsigned long long carry = 0;\n";
    out << "        for (int i = 7; i >= 0; --i) {\n";
    out << "            unsigned long long cur = words[i] + (carry << 32);\n";
    out << "            words[i] = cur / 10;\n";
    out << "            carry = cur % 10;\n";
    out << "        }\n";
    out << "        low = ((unsigned __int128)words[3] << 96) | ((unsigned __int128)words[2] << 64) | ((unsigned __int128)words[1] << 32) | words[0];\n";
    out << "        high = ((__int128)words[7] << 96) | ((__int128)words[6] << 64) | ((__int128)words[5] << 32) | words[4];\n";
    out << "        return (unsigned int)carry;\n";
    out << "    }\n";
    out << "    std::string to_string() const {\n";
    out << "        if (high == 0 && low == 0) return \"0\";\n";
    out << "        bool neg = false;\n";
    out << "        np_int256 temp = *this;\n";
    out << "        if (high < 0) { neg = true; temp = np_int256() - temp; }\n";
    out << "        std::string s = \"\";\n";
    out << "        while (temp.high > 0 || temp.low > 0) {\n";
    out << "            s += (char)('0' + temp.divmod10());\n";
    out << "        }\n";
    out << "        if (neg) s += \"-\";\n";
    out << "        std::reverse(s.begin(), s.end());\n";
    out << "        return s;\n";
    out << "    }\n";
    out << "    operator double() const {\n";
    out << "        return (double)high * std::pow(2.0, 128) + (double)low;\n";
    out << "    }\n";
    out << "    operator int64_t() const { return (int64_t)low; }\n";
    out << "    friend std::ostream& operator<<(std::ostream& os, const np_int256& val) { os << val.to_string(); return os; }\n";
    out << "    friend np_int256 operator+(np_int256 a, np_int256 b) {\n";
    out << "        unsigned __int128 low = a.low + b.low;\n";
    out << "        __int128 high = a.high + b.high;\n";
    out << "        if (low < a.low) high += 1;\n";
    out << "        return np_int256(low, high);\n";
    out << "    }\n";
    out << "    friend np_int256 operator-(np_int256 a, np_int256 b) {\n";
    out << "        unsigned __int128 low = a.low - b.low;\n";
    out << "        __int128 high = a.high - b.high;\n";
    out << "        if (a.low < b.low) high -= 1;\n";
    out << "        return np_int256(low, high);\n";
    out << "    }\n";
    out << "    static np_int256 multiply128(unsigned __int128 x, unsigned __int128 y) {\n";
    out << "        uint64_t x1 = x >> 64, x0 = x & 0xFFFFFFFFFFFFFFFFULL;\n";
    out << "        uint64_t y1 = y >> 64, y0 = y & 0xFFFFFFFFFFFFFFFFULL;\n";
    out << "        unsigned __int128 p00 = (unsigned __int128)x0 * y0;\n";
    out << "        unsigned __int128 p01 = (unsigned __int128)x0 * y1;\n";
    out << "        unsigned __int128 p10 = (unsigned __int128)x1 * y0;\n";
    out << "        unsigned __int128 p11 = (unsigned __int128)x1 * y1;\n";
    out << "        unsigned __int128 middle = p01 + p10;\n";
    out << "        unsigned __int128 carry = (middle < p01) ? ((unsigned __int128)1 << 64) : 0;\n";
    out << "        unsigned __int128 low = p00 + (middle << 64);\n";
    out << "        if (low < p00) carry += 1;\n";
    out << "        __int128 high = p11 + (middle >> 64) + carry;\n";
    out << "        return np_int256(low, high);\n";
    out << "    }\n";
    out << "    friend np_int256 operator*(np_int256 a, np_int256 b) {\n";
    out << "        np_int256 res = np_int256::multiply128(a.low, b.low);\n";
    out << "        res.high += (a.high * b.low) + (a.low * b.high);\n";
    out << "        return res;\n";
    out << "    }\n";
    out << "    friend np_int256 shift_left(np_int256 a, int shift) {\n";
    out << "        if (shift <= 0) return a;\n";
    out << "        if (shift >= 256) return np_int256(0, 0);\n";
    out << "        if (shift >= 128) return np_int256(0, a.low << (shift - 128));\n";
    out << "        unsigned __int128 low = a.low << shift;\n";
    out << "        __int128 high = (a.high << shift) | (a.low >> (128 - shift));\n";
    out << "        return np_int256(low, high);\n";
    out << "    }\n";
    out << "    friend np_int256 shift_right_logical(np_int256 a, int shift) {\n";
    out << "        if (shift <= 0) return a;\n";
    out << "        if (shift >= 256) return np_int256(0, 0);\n";
    out << "        unsigned __int128 a_high = (unsigned __int128)a.high;\n";
    out << "        if (shift >= 128) return np_int256(a_high >> (shift - 128), 0);\n";
    out << "        unsigned __int128 low = (a.low >> shift) | (a_high << (128 - shift));\n";
    out << "        __int128 high = a_high >> shift;\n";
    out << "        return np_int256(low, high);\n";
    out << "    }\n";
    out << "    friend void divmod256(np_int256 num, np_int256 den, np_int256& quot, np_int256& rem) {\n";
    out << "        if (den.high == 0 && den.low == 0) { quot = np_int256(0,0); rem = np_int256(0,0); return; }\n";
    out << "        bool num_neg = num.high < 0;\n";
    out << "        bool den_neg = den.high < 0;\n";
    out << "        np_int256 u_num = num_neg ? (np_int256(0,0) - num) : num;\n";
    out << "        np_int256 u_den = den_neg ? (np_int256(0,0) - den) : den;\n";
    out << "        np_int256 q(0,0);\n";
    out << "        np_int256 r(0,0);\n";
    out << "        for (int i = 255; i >= 0; --i) {\n";
    out << "            r = shift_left(r, 1);\n";
    out << "            unsigned int bit = 0;\n";
    out << "            if (i >= 128) bit = (unsigned int)((u_num.high >> (i - 128)) & 1);\n";
    out << "            else bit = (unsigned int)((u_num.low >> i) & 1);\n";
    out << "            r.low |= bit;\n";
    out << "            if (r >= u_den) {\n";
    out << "                r = r - u_den;\n";
    out << "                if (i >= 128) q.high |= ((__int128)1 << (i - 128));\n";
    out << "                else q.low |= ((unsigned __int128)1 << i);\n";
    out << "            }\n";
    out << "        }\n";
    out << "        if (num_neg ^ den_neg) quot = np_int256(0,0) - q;\n";
    out << "        else quot = q;\n";
    out << "        if (num_neg) rem = np_int256(0,0) - r;\n";
    out << "        else rem = r;\n";
    out << "    }\n";
    out << "    friend np_int256 operator/(np_int256 a, np_int256 b) { np_int256 q, r; divmod256(a, b, q, r); return q; }\n";
    out << "    friend np_int256 operator%(np_int256 a, np_int256 b) { np_int256 q, r; divmod256(a, b, q, r); return r; }\n";
    out << "    friend bool operator==(np_int256 a, np_int256 b) { return a.low == b.low && a.high == b.high; }\n";
    out << "    friend bool operator!=(np_int256 a, np_int256 b) { return !(a == b); }\n";
    out << "    friend bool operator<(np_int256 a, np_int256 b) {\n";
    out << "        if (a.high != b.high) return a.high < b.high;\n";
    out << "        return a.low < b.low;\n";
    out << "    }\n";
    out << "    friend bool operator>(np_int256 a, np_int256 b) { return b < a; }\n";
    out << "    friend bool operator<=(np_int256 a, np_int256 b) { return !(b < a); }\n";
    out << "    friend bool operator>=(np_int256 a, np_int256 b) { return !(a < b); }\n";
    out << "    NP_INT_PRIMITIVE_OPS(np_int256, int)\n";
    out << "    NP_INT_PRIMITIVE_OPS(np_int256, int64_t)\n";
    out << "};\n\n";

    out << "struct np_var;\n";
    out << "struct np_var_list;\n";
    out << "struct np_var_dict;\n";
    out << "using ListPtr = np_var_list*;\n"; // Change shared_ptr to raw pointer
    out << "using DictPtr = np_var_dict*;\n";
    out << "struct np_var {\n";
    out << "    std::variant<int64_t, double, np_string, bool, ListPtr, DictPtr, np_int128, np_int256> v;\n";
    out << "    np_var() : v(0) {}\n";
    out << "    np_var(int val) : v(static_cast<int64_t>(val)) {}\n";
    out << "    np_var(int64_t val) : v(val) {}\n";
    out << "    np_var(double val) : v(val) {}\n";
    out << "    np_var(const char* val) : v(np_string(val)) {}\n";
    out << "    np_var(np_string val) : v(val) {}\n";
    out << "    np_var(std::string val) : v(np_string(val)) {}\n";
    out << "    np_var(bool val) : v(val) {}\n";
    out << "    np_var(np_int128 val) : v(val) {}\n";
    out << "    np_var(np_int256 val) : v(val) {}\n";
    out << "    np_var(const std::vector<np_var>& val);\n";
    out << "    np_var(const std::map<std::string, np_var>& val);\n";
    out << "    np_var(ListPtr val) : v(val) {}\n";
    out << "    np_var(DictPtr val) : v(val) {}\n";
    
    out << "    operator int64_t() const;\n";
    out << "    operator double() const;\n";
    out << "    operator np_string() const;\n";
    out << "    operator bool() const;\n";
    out << "    operator np_int128() const;\n";
    out << "    operator np_int256() const;\n";
    out << "    np_string to_string() const;\n";
    out << "    int length() const;\n";
    out << "    np_var shape() const;\n";
    out << "    bool has_key(const std::string& key) const;\n";
    out << "    bool has_key(const char* key) const;\n";
    out << "    void append(const np_var& val);\n";
    out << "    np_var pop();\n";
    out << "    void clear();\n";
    out << "    np_var keys() const;\n";
    out << "    np_var values() const;\n";
    out << "    np_var slice(int start, int end) const;\n";
    out << "    void sort();\n";
    out << "    void reverse();\n";
    out << "    bool contains(const np_var& val) const;\n";
    out << "    np_var split(const np_var& delim) const;\n";
    out << "    np_var join(const np_var& arr) const;\n";
    out << "    np_var trim() const;\n";
    out << "    using const_iterator = const np_var*;\n";
    out << "    const_iterator begin() const;\n";
    out << "    const_iterator end() const;\n";
    out << "    friend std::ostream& operator<<(std::ostream& os, const np_var& var);\n";
    out << "    np_var& operator[](int index);\n";
    out << "    np_var& operator[](const std::string& key);\n";
    out << "    np_var& operator[](const char* key);\n";
    
    out << "    np_var operator+(const np_var& o) const;\n";
    out << "    np_var operator^(const np_var& o) const;\n";
    out << "#define NP_MATH_OP(op) np_var operator op(const np_var& o) const;\n";
    out << "    NP_MATH_OP(-)\n    NP_MATH_OP(*)\n    NP_MATH_OP(/)\n    NP_MATH_OP(%)\n";
    out << "#define NP_CMP_OP(op) bool operator op(const np_var& o) const;\n";
    out << "    NP_CMP_OP(>)\n    NP_CMP_OP(<)\n    NP_CMP_OP(>=)\n    NP_CMP_OP(<=)\n    NP_CMP_OP(==)\n    NP_CMP_OP(!=)\n";
    out << "};\n\n";
    
    out << "struct np_var_list { std::vector<np_var> vec; np_var_list(const std::vector<np_var>& v) : vec(v) {} void* operator new(size_t size) { return GC_MALLOC(size); } void operator delete(void* ptr) {} };\n";
    out << "struct np_var_dict { std::map<std::string, np_var> map; np_var_dict(const std::map<std::string, np_var>& m) : map(m) {} void* operator new(size_t size) { return GC_MALLOC(size); } void operator delete(void* ptr) {} };\n\n";
    out << "inline np_var::np_var(const std::vector<np_var>& val) : v(new np_var_list(val)) {}\n";
    out << "inline np_var::np_var(const std::map<std::string, np_var>& val) : v(new np_var_dict(val)) {}\n";
    
    out << "inline np_int256 to_int256(const np_var& var) {\n";
    out << "    if (std::holds_alternative<np_int256>(var.v)) return std::get<np_int256>(var.v);\n";
    out << "    if (std::holds_alternative<np_int128>(var.v)) return np_int256(std::get<np_int128>(var.v));\n";
    out << "    if (std::holds_alternative<int64_t>(var.v)) return np_int256(std::get<int64_t>(var.v));\n";
    out << "    if (std::holds_alternative<double>(var.v)) return np_int256(static_cast<int64_t>(std::get<double>(var.v)));\n";
    out << "    if (std::holds_alternative<np_string>(var.v)) return np_int256(std::get<np_string>(var.v).c_str());\n";
    out << "    return np_int256();\n";
    out << "}\n";
    out << "inline np_int128 to_int128(const np_var& var) {\n";
    out << "    if (std::holds_alternative<np_int128>(var.v)) return std::get<np_int128>(var.v);\n";
    out << "    if (std::holds_alternative<np_int256>(var.v)) return np_int128(std::get<np_int256>(var.v).low);\n";
    out << "    if (std::holds_alternative<int64_t>(var.v)) return np_int128(std::get<int64_t>(var.v));\n";
    out << "    if (std::holds_alternative<double>(var.v)) return np_int128(static_cast<int64_t>(std::get<double>(var.v)));\n";
    out << "    if (std::holds_alternative<np_string>(var.v)) return np_int128(std::get<np_string>(var.v).c_str());\n";
    out << "    return np_int128();\n";
    out << "}\n";

    out << "inline np_var::operator int64_t() const { if(std::holds_alternative<int64_t>(v)) return std::get<int64_t>(v); if(std::holds_alternative<double>(v)) return static_cast<int64_t>(std::get<double>(v)); if(std::holds_alternative<np_int128>(v)) return static_cast<int64_t>(std::get<np_int128>(v)); if(std::holds_alternative<np_int256>(v)) return static_cast<int64_t>(std::get<np_int256>(v).low); return 0; }\n";
    out << "inline np_var::operator double() const { if(std::holds_alternative<double>(v)) return std::get<double>(v); if(std::holds_alternative<int64_t>(v)) return static_cast<double>(std::get<int64_t>(v)); if(std::holds_alternative<np_int128>(v)) return static_cast<double>(std::get<np_int128>(v)); if(std::holds_alternative<np_int256>(v)) return static_cast<double>(std::get<np_int256>(v).low); return 0.0; }\n";
    out << "inline np_var::operator np_string() const { return np_string(to_string()); }\n";
    out << "inline np_var::operator bool() const { if(std::holds_alternative<bool>(v)) return std::get<bool>(v); return false; }\n";
    out << "inline np_var::operator np_int128() const { return to_int128(*this); }\n";
    out << "inline np_var::operator np_int256() const { return to_int256(*this); }\n";
    
    out << "inline np_string np_var::to_string() const {\n";
    out << "    if (std::holds_alternative<int64_t>(v)) return std::to_string(std::get<int64_t>(v));\n";
    out << "    if (std::holds_alternative<double>(v)) {\n";
    out << "        std::string s = std::to_string(std::get<double>(v));\n";
    out << "        s.erase(s.find_last_not_of('0') + 1, std::string::npos); if (s.back() == '.') s += \"0\"; return s;\n";
    out << "    }\n";
    out << "    if (std::holds_alternative<np_string>(v)) return std::get<np_string>(v);\n";
    out << "    if (std::holds_alternative<bool>(v)) return std::get<bool>(v) ? \"true\" : \"false\";\n";
    out << "    if (std::holds_alternative<np_int128>(v)) return std::get<np_int128>(v).to_string();\n";
    out << "    if (std::holds_alternative<np_int256>(v)) return std::get<np_int256>(v).to_string();\n";
    out << "    if (std::holds_alternative<ListPtr>(v)) {\n";
    out << "        std::string s = \"[\"; auto arr = std::get<ListPtr>(v);\n";
    out << "        if (arr) { for (size_t i = 0; i < arr->vec.size(); ++i) { s += arr->vec[i].to_string(); if (i < arr->vec.size() - 1) s += \", \"; } }\n";
    out << "        return s + \"]\";\n";
    out << "    }\n";
    out << "    if (std::holds_alternative<DictPtr>(v)) {\n";
    out << "        std::string s = \"{\"; auto dict = std::get<DictPtr>(v);\n";
    out << "        if (dict) { bool first = true; for (auto const& [k, val] : dict->map) { if (!first) s += \", \"; s += \"\\\"\" + k + \"\\\": \" + static_cast<std::string>(val.to_string()); first = false; } }\n";
    out << "        return s + \"}\";\n";
    out << "    }\n";
    out << "    return \"\";\n";
    out << "}\n";
    
    out << "inline int np_var::length() const {\n";
    out << "    if (std::holds_alternative<ListPtr>(v) && std::get<ListPtr>(v)) return std::get<ListPtr>(v)->vec.size();\n";
    out << "    if (std::holds_alternative<DictPtr>(v) && std::get<DictPtr>(v)) return std::get<DictPtr>(v)->map.size();\n";
    out << "    if (std::holds_alternative<np_string>(v)) return std::get<np_string>(v).length();\n";
    out << "    return 0;\n";
    out << "}\n";
    
    out << "inline np_var np_var::shape() const {\n";
    out << "    if (!std::holds_alternative<ListPtr>(v) || !std::get<ListPtr>(v)) return std::vector<np_var>{};\n";
    out << "    std::vector<np_var> dims;\n";
    out << "    np_var current = *this;\n";
    out << "    while (std::holds_alternative<ListPtr>(current.v) && std::get<ListPtr>(current.v)) {\n";
    out << "        auto& vec = std::get<ListPtr>(current.v)->vec;\n";
    out << "        dims.push_back(static_cast<int>(vec.size()));\n";
    out << "        if (vec.empty()) break; current = vec[0];\n";
    out << "    }\n";
    out << "    return dims;\n";
    out << "}\n";
    
    out << "inline bool np_var::has_key(const std::string& key) const {\n";
    out << "    if (std::holds_alternative<DictPtr>(v) && std::get<DictPtr>(v)) return std::get<DictPtr>(v)->map.count(key) > 0;\n";
    out << "    return false;\n";
    out << "}\n";
    out << "inline bool np_var::has_key(const char* key) const { return has_key(std::string(key)); }\n";
    
    out << "inline void np_var::append(const np_var& val) {\n";
    out << "    if (std::holds_alternative<ListPtr>(v) && std::get<ListPtr>(v)) std::get<ListPtr>(v)->vec.push_back(val);\n";
    out << "}\n";
    
    out << "inline np_var np_var::pop() {\n    if (std::holds_alternative<ListPtr>(v) && std::get<ListPtr>(v)) {\n        auto& vec = std::get<ListPtr>(v)->vec;\n        if (!vec.empty()) { np_var last = vec.back(); vec.pop_back(); return last; }\n    }\n    return np_var();\n}\ninline void np_var::clear() {\n    if (std::holds_alternative<ListPtr>(v) && std::get<ListPtr>(v)) std::get<ListPtr>(v)->vec.clear();\n    else if (std::holds_alternative<DictPtr>(v) && std::get<DictPtr>(v)) std::get<DictPtr>(v)->map.clear();\n}\ninline np_var np_var::keys() const {\n    if (std::holds_alternative<DictPtr>(v) && std::get<DictPtr>(v)) {\n        std::vector<np_var> k_vec;\n        for (auto const& [k, val] : std::get<DictPtr>(v)->map) k_vec.push_back(k);\n        return np_var(k_vec);\n    }\n    return np_var(std::vector<np_var>{});\n}\ninline np_var np_var::values() const {\n    if (std::holds_alternative<DictPtr>(v) && std::get<DictPtr>(v)) {\n        std::vector<np_var> v_vec;\n        for (auto const& [k, val] : std::get<DictPtr>(v)->map) v_vec.push_back(val);\n        return np_var(v_vec);\n    }\n    return np_var(std::vector<np_var>{});\n}\ninline np_var np_var::slice(int start, int end) const {\n    if (std::holds_alternative<ListPtr>(v) && std::get<ListPtr>(v)) {\n        auto const& vec = std::get<ListPtr>(v)->vec;\n        int len = vec.size();\n        if (end == -999999) end = len;\n        if (start < 0) start += len; if (start < 0) start = 0; if (start > len) start = len;\n        if (end < 0) end += len; if (end < 0) end = 0; if (end > len) end = len;\n        if (end < start) end = start;\n        std::vector<np_var> res_vec;\n        for (int i = start; i < end; ++i) res_vec.push_back(vec[i]);\n        return np_var(res_vec);\n    }\n    if (std::holds_alternative<np_string>(v)) {\n        np_string s = std::get<np_string>(v);\n        int len = s.length();\n        if (end == -999999) end = len;\n        if (start < 0) start += len; if (start < 0) start = 0; if (start > len) start = len;\n        if (end < 0) end += len; if (end < 0) end = 0; if (end > len) end = len;\n        if (end < start) end = start;\n        return s.substr(start, end - start);\n    }\n    return np_var();\n}\ninline np_var::const_iterator np_var::begin() const {\n    if (std::holds_alternative<ListPtr>(v) && std::get<ListPtr>(v)) return std::get<ListPtr>(v)->vec.data();\n    return nullptr;\n}\ninline np_var::const_iterator np_var::end() const {\n    if (std::holds_alternative<ListPtr>(v) && std::get<ListPtr>(v)) return std::get<ListPtr>(v)->vec.data() + std::get<ListPtr>(v)->vec.size();\n    return nullptr;\n}\ninline std::ostream& operator<<(std::ostream& os, const np_var& var) { os << var.to_string(); return os; }\ninline np_var& np_var::operator[](int index) { return std::get<ListPtr>(v)->vec[index]; }\ninline np_var& np_var::operator[](const std::string& key) { return std::get<DictPtr>(v)->map[key]; }\ninline np_var& np_var::operator[](const char* key) { return std::get<DictPtr>(v)->map[std::string(key)]; }\n\ninline np_var np_var::operator+(const np_var& o) const {\n    if (std::holds_alternative<np_int256>(v) || std::holds_alternative<np_int256>(o.v)) return np_var(to_int256(*this) + to_int256(o));\n    if (std::holds_alternative<np_int128>(v) || std::holds_alternative<np_int128>(o.v)) return np_var(to_int128(*this) + to_int128(o));\n    if(std::holds_alternative<ListPtr>(v) && std::holds_alternative<ListPtr>(o.v)) {\n        auto a_ptr = std::get<ListPtr>(v); auto b_ptr = std::get<ListPtr>(o.v);\n        if (a_ptr && b_ptr) {\n            std::vector<np_var> res_vec; size_t min_sz = std::min(a_ptr->vec.size(), b_ptr->vec.size());\n            for (size_t i = 0; i < min_sz; ++i) res_vec.push_back(a_ptr->vec[i] + b_ptr->vec[i]);\n            return np_var(res_vec);\n        }\n    }\n    if (std::holds_alternative<ListPtr>(v) && !std::holds_alternative<ListPtr>(o.v) && !std::holds_alternative<DictPtr>(o.v)) {\n        auto a_ptr = std::get<ListPtr>(v);\n        if (a_ptr) {\n            std::vector<np_var> res_vec;\n            for (size_t i = 0; i < a_ptr->vec.size(); ++i) res_vec.push_back(a_ptr->vec[i] + o);\n            return np_var(res_vec);\n        }\n    }\n    if (!std::holds_alternative<ListPtr>(v) && !std::holds_alternative<DictPtr>(v) && std::holds_alternative<ListPtr>(o.v)) {\n        auto b_ptr = std::get<ListPtr>(o.v);\n        if (b_ptr) {\n            std::vector<np_var> res_vec;\n            for (size_t i = 0; i < b_ptr->vec.size(); ++i) res_vec.push_back((*this) + b_ptr->vec[i]);\n            return np_var(res_vec);\n        }\n    }\n    if(std::holds_alternative<np_string>(v) || std::holds_alternative<np_string>(o.v)) return to_string() + o.to_string();\n    if(std::holds_alternative<int64_t>(v) && std::holds_alternative<int64_t>(o.v)) return std::get<int64_t>(v) + std::get<int64_t>(o.v);\n    if(std::holds_alternative<double>(v) && std::holds_alternative<double>(o.v)) return std::get<double>(v) + std::get<double>(o.v);\n    if(std::holds_alternative<int64_t>(v) && std::holds_alternative<double>(o.v)) return std::get<int64_t>(v) + std::get<double>(o.v);\n    if(std::holds_alternative<double>(v) && std::holds_alternative<int64_t>(o.v)) return std::get<double>(v) + std::get<int64_t>(o.v);\n    return 0;\n}\ninline np_var np_var::operator^(const np_var& o) const {\n    if(std::holds_alternative<ListPtr>(v) && std::holds_alternative<ListPtr>(o.v)) {\n        auto a_ptr = std::get<ListPtr>(v); auto b_ptr = std::get<ListPtr>(o.v);\n        if (a_ptr && b_ptr) {\n            std::vector<np_var> res_vec; size_t min_sz = std::min(a_ptr->vec.size(), b_ptr->vec.size());\n            for (size_t i = 0; i < min_sz; ++i) res_vec.push_back(a_ptr->vec[i] ^ b_ptr->vec[i]);\n            return np_var(res_vec);\n        }\n    }\n    if (std::holds_alternative<ListPtr>(v) && !std::holds_alternative<ListPtr>(o.v) && !std::holds_alternative<DictPtr>(o.v)) {\n        auto a_ptr = std::get<ListPtr>(v);\n        if (a_ptr) {\n            std::vector<np_var> res_vec;\n            for (size_t i = 0; i < a_ptr->vec.size(); ++i) res_vec.push_back(a_ptr->vec[i] ^ o);\n            return np_var(res_vec);\n        }\n    }\n    if (!std::holds_alternative<ListPtr>(v) && !std::holds_alternative<DictPtr>(v) && std::holds_alternative<ListPtr>(o.v)) {\n        auto b_ptr = std::get<ListPtr>(o.v);\n        if (b_ptr) {\n            std::vector<np_var> res_vec;\n            for (size_t i = 0; i < b_ptr->vec.size(); ++i) res_vec.push_back((*this) ^ b_ptr->vec[i]);\n            return np_var(res_vec);\n        }\n    }\n    if(std::holds_alternative<int64_t>(v) && std::holds_alternative<int64_t>(o.v)) return static_cast<int64_t>(std::pow(std::get<int64_t>(v), std::get<int64_t>(o.v)));\n    if(std::holds_alternative<double>(v) && std::holds_alternative<double>(o.v)) return std::pow(std::get<double>(v), std::get<double>(o.v));\n    if(std::holds_alternative<int64_t>(v) && std::holds_alternative<double>(o.v)) return std::pow(std::get<int64_t>(v), std::get<double>(o.v));\n    if(std::holds_alternative<double>(v) && std::holds_alternative<int64_t>(o.v)) return std::pow(std::get<double>(v), std::get<int64_t>(o.v));\n    return 0;\n}\n#define NP_MATH_OP_IMPL(op) inline np_var np_var::operator op(const np_var& o) const { \\\n    if (std::holds_alternative<np_int256>(v) || std::holds_alternative<np_int256>(o.v)) return np_var(to_int256(*this) op to_int256(o)); \\\n    if (std::holds_alternative<np_int128>(v) || std::holds_alternative<np_int128>(o.v)) return np_var(to_int128(*this) op to_int128(o)); \\\n    if(std::holds_alternative<ListPtr>(v) && std::holds_alternative<ListPtr>(o.v)) { \\\n        auto a_ptr = std::get<ListPtr>(v); auto b_ptr = std::get<ListPtr>(o.v); \\\n        if (a_ptr && b_ptr) { \\\n            std::vector<np_var> res_vec; size_t min_sz = std::min(a_ptr->vec.size(), b_ptr->vec.size()); \\\n            for (size_t i = 0; i < min_sz; ++i) res_vec.push_back(a_ptr->vec[i] op b_ptr->vec[i]); \\\n            return np_var(res_vec); \\\n        } \\\n    } \\\n    if (std::holds_alternative<ListPtr>(v) && !std::holds_alternative<ListPtr>(o.v) && !std::holds_alternative<DictPtr>(o.v)) { \\\n        auto a_ptr = std::get<ListPtr>(v); \\\n        if (a_ptr) { \\\n            std::vector<np_var> res_vec; \\\n            for (size_t i = 0; i < a_ptr->vec.size(); ++i) res_vec.push_back(a_ptr->vec[i] op o); \\\n            return np_var(res_vec); \\\n        } \\\n    } \\\n    if (!std::holds_alternative<ListPtr>(v) && !std::holds_alternative<DictPtr>(v) && std::holds_alternative<ListPtr>(o.v)) { \\\n        auto b_ptr = std::get<ListPtr>(o.v); \\\n        if (b_ptr) { \\\n            std::vector<np_var> res_vec; \\\n            for (size_t i = 0; i < b_ptr->vec.size(); ++i) res_vec.push_back((*this) op b_ptr->vec[i]); \\\n            return np_var(res_vec); \\\n        } \\\n    } \\\n    if(std::holds_alternative<int64_t>(v) && std::holds_alternative<int64_t>(o.v)) return std::get<int64_t>(v) op std::get<int64_t>(o.v); \\\n    if(std::holds_alternative<double>(v) && std::holds_alternative<double>(o.v)) return std::get<double>(v) op std::get<double>(o.v); \\\n    if(std::holds_alternative<int64_t>(v) && std::holds_alternative<double>(o.v)) return std::get<int64_t>(v) op std::get<double>(o.v); \\\n    if(std::holds_alternative<double>(v) && std::holds_alternative<int64_t>(o.v)) return std::get<double>(v) op std::get<int64_t>(o.v); \\\n    return 0; \\\n}\nNP_MATH_OP_IMPL(-)\nNP_MATH_OP_IMPL(*)\nNP_MATH_OP_IMPL(/)\ninline np_var np_var::operator%(const np_var& o) const {\n    if (std::holds_alternative<np_int256>(v) || std::holds_alternative<np_int256>(o.v)) return np_var(to_int256(*this) % to_int256(o));\n    if (std::holds_alternative<np_int128>(v) || std::holds_alternative<np_int128>(o.v)) return np_var(to_int128(*this) % to_int128(o));\n    if(std::holds_alternative<ListPtr>(v) && std::holds_alternative<ListPtr>(o.v)) {\n        auto a_ptr = std::get<ListPtr>(v); auto b_ptr = std::get<ListPtr>(o.v);\n        if (a_ptr && b_ptr) {\n            std::vector<np_var> res_vec; size_t min_sz = std::min(a_ptr->vec.size(), b_ptr->vec.size());\n            for (size_t i = 0; i < min_sz; ++i) res_vec.push_back(a_ptr->vec[i] % b_ptr->vec[i]);\n            return np_var(res_vec);\n        }\n    }\n    if (std::holds_alternative<ListPtr>(v) && !std::holds_alternative<ListPtr>(o.v) && !std::holds_alternative<DictPtr>(o.v)) {\n        auto a_ptr = std::get<ListPtr>(v);\n        if (a_ptr) {\n            std::vector<np_var> res_vec;\n            for (size_t i = 0; i < a_ptr->vec.size(); ++i) res_vec.push_back(a_ptr->vec[i] % o);\n            return np_var(res_vec);\n        }\n    }\n    if (!std::holds_alternative<ListPtr>(v) && !std::holds_alternative<DictPtr>(v) && std::holds_alternative<ListPtr>(o.v)) {\n        auto b_ptr = std::get<ListPtr>(o.v);\n        if (b_ptr) {\n            std::vector<np_var> res_vec;\n            for (size_t i = 0; i < b_ptr->vec.size(); ++i) res_vec.push_back((*this) % b_ptr->vec[i]);\n            return np_var(res_vec);\n        }\n    }\n    if(std::holds_alternative<int64_t>(v) && std::holds_alternative<int64_t>(o.v)) return std::get<int64_t>(v) % std::get<int64_t>(o.v);\n    if(std::holds_alternative<double>(v) && std::holds_alternative<double>(o.v)) return std::fmod(std::get<double>(v), std::get<double>(o.v));\n    if(std::holds_alternative<int64_t>(v) && std::holds_alternative<double>(o.v)) return std::fmod(static_cast<double>(std::get<int64_t>(v)), std::get<double>(o.v));\n    if(std::holds_alternative<double>(v) && std::holds_alternative<int64_t>(o.v)) return std::fmod(std::get<double>(v), static_cast<double>(std::get<int64_t>(o.v)));\n    return 0;\n}\n#define NP_CMP_OP_IMPL(op) inline bool np_var::operator op(const np_var& o) const { \\\n    if (std::holds_alternative<np_int256>(v) || std::holds_alternative<np_int256>(o.v)) return to_int256(*this) op to_int256(o); \\\n    if (std::holds_alternative<np_int128>(v) || std::holds_alternative<np_int128>(o.v)) return to_int128(*this) op to_int128(o); \\\n    if(std::holds_alternative<int64_t>(v) && std::holds_alternative<int64_t>(o.v)) return std::get<int64_t>(v) op std::get<int64_t>(o.v); \\\n    if(std::holds_alternative<double>(v) && std::holds_alternative<double>(o.v)) return std::get<double>(v) op std::get<double>(o.v); \\\n    if(std::holds_alternative<int64_t>(v) && std::holds_alternative<double>(o.v)) return std::get<int64_t>(v) op std::get<double>(o.v); \\\n    if(std::holds_alternative<double>(v) && std::holds_alternative<int64_t>(o.v)) return std::get<double>(v) op std::get<int64_t>(o.v); \\\n    if(std::holds_alternative<np_string>(v) && std::holds_alternative<np_string>(o.v)) return std::get<np_string>(v) op std::get<np_string>(o.v); \\\n    if(std::holds_alternative<bool>(v) && std::holds_alternative<bool>(o.v)) return std::get<bool>(v) op std::get<bool>(o.v); \\\n    return false; \\\n}\nNP_CMP_OP_IMPL(>)\nNP_CMP_OP_IMPL(<)\nNP_CMP_OP_IMPL(>=)\nNP_CMP_OP_IMPL(<=)\nNP_CMP_OP_IMPL(==)\nNP_CMP_OP_IMPL(!=)\n\n";
    
    out << "inline void np_var::sort() {\n";
    out << "    if (std::holds_alternative<ListPtr>(v) && std::get<ListPtr>(v)) {\n";
    out << "        std::sort(std::get<ListPtr>(v)->vec.begin(), std::get<ListPtr>(v)->vec.end());\n";
    out << "    }\n";
    out << "}\n";
    out << "inline void np_var::reverse() {\n";
    out << "    if (std::holds_alternative<ListPtr>(v) && std::get<ListPtr>(v)) {\n";
    out << "        std::reverse(std::get<ListPtr>(v)->vec.begin(), std::get<ListPtr>(v)->vec.end());\n";
    out << "    }\n";
    out << "}\n";
    out << "inline bool np_var::contains(const np_var& val) const {\n";
    out << "    if (std::holds_alternative<ListPtr>(v) && std::get<ListPtr>(v)) {\n";
    out << "        auto const& vec = std::get<ListPtr>(v)->vec;\n";
    out << "        for (auto const& item : vec) {\n";
    out << "            if (item == val) return true;\n";
    out << "        }\n";
    out << "    }\n";
    out << "    if (std::holds_alternative<DictPtr>(v) && std::get<DictPtr>(v)) {\n";
    out << "        return std::get<DictPtr>(v)->map.count(static_cast<std::string>(val)) > 0;\n";
    out << "    }\n";
    out << "    if (std::holds_alternative<np_string>(v)) {\n";
    out << "        return std::get<np_string>(v).find(static_cast<std::string>(val)) != std::string::npos;\n";
    out << "    }\n";
    out << "    return false;\n";
    out << "}\n";
    out << "inline np_var np_var::split(const np_var& delim) const {\n";
    out << "    if (std::holds_alternative<np_string>(v)) return std::get<np_string>(v).split(static_cast<std::string>(delim));\n";
    out << "    return np_var(std::vector<np_var>{});\n";
    out << "}\n";
    out << "inline np_var np_var::join(const np_var& arr) const {\n";
    out << "    if (std::holds_alternative<np_string>(v)) return std::get<np_string>(v).join(arr);\n";
    out << "    return np_var(\"\");\n";
    out << "}\n";
    out << "inline np_var np_var::trim() const {\n";
    out << "    if (std::holds_alternative<np_string>(v)) return std::get<np_string>(v).trim();\n";
    out << "    return *this;\n";
    out << "}\n";
    
    out << "inline np_var np_string::split(const std::string& delim) const {\n";
    out << "    std::vector<np_var> res;\n";
    out << "    size_t start = 0;\n";
    out << "    size_t end = this->find(delim);\n";
    out << "    while (end != std::string::npos) {\n";
    out << "        res.push_back(this->substr(start, end - start));\n";
    out << "        start = end + delim.length();\n";
    out << "        end = this->find(delim, start);\n";
    out << "    }\n";
    out << "    res.push_back(this->substr(start));\n";
    out << "    return np_var(res);\n";
    out << "}\n";
    out << "inline np_string np_string::join(const np_var& arr) const {\n";
    out << "    std::string res = \"\";\n";
    out << "    if (std::holds_alternative<ListPtr>(arr.v) && std::get<ListPtr>(arr.v)) {\n";
    out << "        auto const& vec = std::get<ListPtr>(arr.v)->vec;\n";
    out << "        for (size_t i = 0; i < vec.size(); ++i) {\n";
    out << "            res += static_cast<std::string>(vec[i]);\n";
    out << "            if (i < vec.size() - 1) res += *this;\n";
    out << "        }\n";
    out << "    }\n";
    out << "    return np_string(res);\n";
    out << "}\n";
    out << "inline np_string np_string::trim() const {\n";
    out << "    size_t first = this->find_first_not_of(\" \\t\\r\\n\");\n";
    out << "    if (first == std::string::npos) return \"\";\n";
    out << "    size_t last = this->find_last_not_of(\" \\t\\r\\n\");\n";
    out << "    return this->substr(first, last - first + 1);\n";
    out << "}\n\n";

    out << "inline np_var operator+(int64_t lhs, const np_var& rhs) { return np_var(lhs) + rhs; }\n";
    out << "inline np_var operator+(int lhs, const np_var& rhs) { return np_var(static_cast<int64_t>(lhs)) + rhs; }\n";
    out << "inline np_var operator+(double lhs, const np_var& rhs) { return np_var(lhs) + rhs; }\n";
    out << "inline np_var operator+(const np_string& lhs, const np_var& rhs) { return np_var(lhs) + rhs; }\n";
    out << "inline np_var operator+(const std::string& lhs, const np_var& rhs) { return np_var(lhs) + rhs; }\n";
    out << "inline np_var operator+(const char* lhs, const np_var& rhs) { return np_var(lhs) + rhs; }\n";
    out << "inline np_var operator+(const np_var& lhs, int64_t rhs) { return lhs + np_var(rhs); }\n";
    out << "inline np_var operator+(const np_var& lhs, int rhs) { return lhs + np_var(static_cast<int64_t>(rhs)); }\n";
    out << "inline np_var operator+(const np_var& lhs, double rhs) { return lhs + np_var(rhs); }\n";
    out << "inline np_var operator+(const np_var& lhs, const np_string& rhs) { return lhs + np_var(rhs); }\n";
    out << "inline np_var operator+(const np_var& lhs, const std::string& rhs) { return lhs + np_var(rhs); }\n";
    out << "inline np_var operator+(const np_var& lhs, const char* rhs) { return lhs + np_var(rhs); }\n";
    out << "#define NP_GLOBAL_MATH_OP(op) \\\n";
    out << "inline np_var operator op(int64_t lhs, const np_var& rhs) { return np_var(lhs) op rhs; } \\\n";
    out << "inline np_var operator op(int lhs, const np_var& rhs) { return np_var(static_cast<int64_t>(lhs)) op rhs; } \\\n";
    out << "inline np_var operator op(double lhs, const np_var& rhs) { return np_var(lhs) op rhs; } \\\n";
    out << "inline np_var operator op(const np_var& lhs, int64_t rhs) { return lhs op np_var(rhs); } \\\n";
    out << "inline np_var operator op(const np_var& lhs, int rhs) { return lhs op np_var(static_cast<int64_t>(rhs)); } \\\n";
    out << "inline np_var operator op(const np_var& lhs, double rhs) { return lhs op np_var(rhs); }\n";
    out << "NP_GLOBAL_MATH_OP(-)\nNP_GLOBAL_MATH_OP(*)\nNP_GLOBAL_MATH_OP(/)\n";
    out << "NP_GLOBAL_MATH_OP(%)\n";
    out << "NP_GLOBAL_MATH_OP(^)\n";
    out << "#define NP_GLOBAL_CMP_OP(op) \\\n";
    out << "inline bool operator op(int64_t lhs, const np_var& rhs) { return np_var(lhs) op rhs; } \\\n";
    out << "inline bool operator op(int lhs, const np_var& rhs) { return np_var(static_cast<int64_t>(lhs)) op rhs; } \\\n";
    out << "inline bool operator op(double lhs, const np_var& rhs) { return np_var(lhs) op rhs; } \\\n";
    out << "inline bool operator op(bool lhs, const np_var& rhs) { return np_var(lhs) op rhs; } \\\n";
    out << "inline bool operator op(const np_string& lhs, const np_var& rhs) { return np_var(lhs) op rhs; } \\\n";
    out << "inline bool operator op(const std::string& lhs, const np_var& rhs) { return np_var(lhs) op rhs; } \\\n";
    out << "inline bool operator op(const char* lhs, const np_var& rhs) { return np_var(lhs) op rhs; } \\\n";
    out << "inline bool operator op(const np_var& lhs, int64_t rhs) { return lhs op np_var(rhs); } \\\n";
    out << "inline bool operator op(const np_var& lhs, int rhs) { return lhs op np_var(static_cast<int64_t>(rhs)); } \\\n";
    out << "inline bool operator op(const np_var& lhs, double rhs) { return lhs op np_var(rhs); } \\\n";
    out << "inline bool operator op(const np_var& lhs, bool rhs) { return lhs op np_var(rhs); } \\\n";
    out << "inline bool operator op(const np_var& lhs, const np_string& rhs) { return lhs op np_var(rhs); } \\\n";
    out << "inline bool operator op(const np_var& lhs, const std::string& rhs) { return lhs op np_var(rhs); } \\\n";
    out << "inline bool operator op(const np_var& lhs, const char* rhs) { return lhs op np_var(rhs); }\n";
    out << "NP_GLOBAL_CMP_OP(>)\nNP_GLOBAL_CMP_OP(<)\nNP_GLOBAL_CMP_OP(>=)\nNP_GLOBAL_CMP_OP(<=)\nNP_GLOBAL_CMP_OP(==)\nNP_GLOBAL_CMP_OP(!=)\n\n";
 
    out << "template<typename T, typename U> auto np_pow_call(T lhs, U rhs) {\n";
    out << "    if constexpr (std::is_same_v<T, np_var> || std::is_same_v<U, np_var>) return np_var(lhs) ^ np_var(rhs);\n";
    out << "    else if constexpr (std::is_floating_point_v<T> || std::is_floating_point_v<U>) return std::pow(static_cast<double>(lhs), static_cast<double>(rhs));\n";
    out << "    else return static_cast<int64_t>(std::pow(static_cast<double>(lhs), static_cast<double>(rhs)));\n";
    out << "}\n";
    out << "struct np_pow_helper_t {} np_pow_helper;\n";
    out << "template<typename LHS> struct np_pow_proxy { LHS lhs; template<typename RHS> auto operator*(RHS rhs) const { return np_pow_call(lhs, rhs); } };\n";
    out << "template<typename LHS> np_pow_proxy<LHS> operator*(LHS lhs, np_pow_helper_t) { return np_pow_proxy<LHS>{lhs}; }\n\n";

    out << "template<typename T> inline double np_sqrt(T v) { return std::sqrt(static_cast<double>(v)); }\n";
    out << "inline double np_sqrt(const np_var& v) { return std::sqrt(static_cast<double>(v)); }\n\n";
    out << "template<typename T> inline auto np_abs(T v) { return std::abs(v); }\n";
    out << "inline np_var np_abs(const np_var& v) {\n";
    out << "    if (std::holds_alternative<double>(v.v)) return std::abs(std::get<double>(v.v));\n";
    out << "    if (std::holds_alternative<int64_t>(v.v)) return std::abs(std::get<int64_t>(v.v));\n";
    out << "    return v;\n";
    out << "}\n\n";
    out << "template<typename T, typename U> auto np_min(T a, U b) {\n";
    out << "    if constexpr (std::is_same_v<T, np_var> || std::is_same_v<U, np_var>) return np_var(a) < np_var(b) ? np_var(a) : np_var(b);\n";
    out << "    else return a < b ? a : b;\n";
    out << "}\n";
    out << "template<typename T, typename U> auto np_max(T a, U b) {\n";
    out << "    if constexpr (std::is_same_v<T, np_var> || std::is_same_v<U, np_var>) return np_var(a) > np_var(b) ? np_var(a) : np_var(b);\n";
    out << "    else return a > b ? a : b;\n";
    out << "}\n\n";
    out << "template<typename T> inline double np_round(T v) { return std::round(static_cast<double>(v)); }\n";
    out << "inline double np_round(const np_var& v) { return std::round(static_cast<double>(v)); }\n\n";
    out << "inline int np_len(const std::string& s) { return s.length(); }\n";
    out << "inline int np_len(const char* s) { return std::string(s).length(); }\n";
    out << "inline int np_len(const np_var& v) { return v.length(); }\n\n";
    out << "inline std::string np_read_file(const std::string& filename) {\n";
    out << "    std::ifstream f(filename);\n";
    out << "    if (!f.is_open()) return \"\";\n";
    out << "    std::stringstream buf;\n";
    out << "    buf << f.rdbuf();\n";
    out << "    return buf.str();\n";
    out << "}\n";
    out << "inline std::string np_read_file(const np_var& filename) { return np_read_file(static_cast<std::string>(filename)); }\n\n";
    out << "inline int np_write_file(const std::string& filename, const std::string& content) {\n";
    out << "    std::ofstream f(filename);\n";
    out << "    if (!f.is_open()) return 0;\n";
    out << "    f << content;\n";
    out << "    return 1;\n";
    out << "}\n";
    out << "inline int np_write_file(const np_var& filename, const np_var& content) { return np_write_file(static_cast<std::string>(filename), static_cast<std::string>(content)); }\n\n";

    // np-lang native standard library implementation
    out << "template<typename T> void np_print(T val) { std::cout << val << std::endl; }\n";
    out << "template<typename T, typename... Args> void np_print(T val, Args... args) { std::cout << val << \" \"; np_print(args...); }\n\n";

    out << "struct np_input_proxy {\n";
    out << "    template<typename T> operator T() { T val; std::cin >> val; std::cin.ignore(10000, '\\n'); return val; }\n";
    out << "    operator std::string() { std::string s; std::getline(std::cin, s); return s; }\n";
    out << "};\n";
    out << "#define np_input() np_input_proxy()\n\n";

    out << "int np_to_int(const std::string& s) { try { return std::stoi(s); } catch(...) { return 0; } }\n";
    out << "int np_to_int(float v) { return static_cast<int>(v); }\n";
    out << "float np_to_float(const std::string& s) { try { return std::stof(s); } catch(...) { return 0.0f; } }\n";
    out << "float np_to_float(int64_t v) { return static_cast<float>(v); }\n";
    out << "std::string np_to_string(int v) { return std::to_string(v); }\n";
    out << "std::string np_to_string(int64_t v) { return std::to_string(v); }\n";
    out << "std::string np_to_string(double v) { return std::to_string(v); }\n\n";

    out << "int np_to_int(const np_var& v) { return static_cast<int>(static_cast<int64_t>(v)); }\n";
    out << "float np_to_float(const np_var& v) { return static_cast<float>(static_cast<double>(v)); }\n";
    out << "std::string np_to_string(const np_var& v) { return v.to_string(); }\n\n";
    
    out << "std::string np_to_string(const np_int128& v) { return v.to_string(); }\n";
    out << "std::string np_to_string(const np_int256& v) { return v.to_string(); }\n";
    out << "int np_to_int(const np_int128& v) { return static_cast<int>(static_cast<int64_t>(v)); }\n";
    out << "int np_to_int(const np_int256& v) { return static_cast<int>(static_cast<int64_t>(v.low)); }\n";
    out << "float np_to_float(const np_int128& v) { return static_cast<float>(static_cast<double>(v)); }\n";
    out << "float np_to_float(const np_int256& v) { return static_cast<float>(static_cast<double>(v.low)); }\n\n";

    out << "template <typename T> std::string np_type(T) { return \"unknown\"; }\n";
    out << "template <> std::string np_type(int) { return \"int32\"; }\n";
    out << "template <> std::string np_type(int64_t) { return \"int64\"; }\n";
    out << "template <> std::string np_type(float) { return \"float32\"; }\n";
    out << "template <> std::string np_type(double) { return \"float64\"; }\n";
    out << "template <> std::string np_type(std::string) { return \"string\"; }\n";
    out << "template <> std::string np_type(np_string) { return \"string\"; }\n";
    out << "template <> std::string np_type(bool) { return \"bool\"; }\n";
    out << "template <> std::string np_type(np_int128) { return \"int128\"; }\n";
    out << "template <> std::string np_type(np_int256) { return \"int256\"; }\n\n";
    out << "template <> std::string np_type(np_var v) { if(std::holds_alternative<int64_t>(v.v)) return \"int\"; if(std::holds_alternative<double>(v.v)) return \"float\"; if(std::holds_alternative<np_string>(v.v)) return \"string\"; if(std::holds_alternative<bool>(v.v)) return \"bool\"; if(std::holds_alternative<ListPtr>(v.v)) return \"array\"; if(std::holds_alternative<DictPtr>(v.v)) return \"dict\"; if(std::holds_alternative<np_int128>(v.v)) return \"int128\"; if(std::holds_alternative<np_int256>(v.v)) return \"int256\"; return \"unknown\"; }\n\n";

    // --- sys module runtime ---
    out << "inline np_var np_sys_argv;\n";
    out << "inline void np_init_args(int argc, char* argv[]) {\n";
    out << "    std::vector<np_var> args;\n";
    out << "    for (int i = 0; i < argc; ++i) {\n";
    out << "        args.push_back(np_var(std::string(argv[i])));\n";
    out << "    }\n";
    out << "    np_sys_argv = np_var(args);\n";
    out << "}\n\n";

    // --- time module runtime ---
    out << "inline double np_time_now() {\n";
    out << "    auto now = std::chrono::system_clock::now();\n";
    out << "    auto duration = now.time_since_epoch();\n";
    out << "    return std::chrono::duration_cast<std::chrono::microseconds>(duration).count() / 1000000.0;\n";
    out << "}\n";
    out << "inline void np_time_sleep(double secs) {\n";
    out << "    std::this_thread::sleep_for(std::chrono::microseconds(static_cast<int64_t>(secs * 1000000.0)));\n";
    out << "}\n";
    out << "inline void np_time_sleep(const np_var& secs) {\n";
    out << "    np_time_sleep(static_cast<double>(secs));\n";
    out << "}\n";
    out << "inline std::string np_time_format(double ts, const std::string& fmt) {\n";
    out << "    std::time_t raw_time = static_cast<std::time_t>(ts);\n";
    out << "    std::tm* timeinfo = std::localtime(&raw_time);\n";
    out << "    if (!timeinfo) return \"\";\n";
    out << "    char buffer[256];\n";
    out << "    std::strftime(buffer, sizeof(buffer), fmt.c_str(), timeinfo);\n";
    out << "    return std::string(buffer);\n";
    out << "}\n";
    out << "inline std::string np_time_format(const np_var& ts, const np_var& fmt) {\n";
    out << "    return np_time_format(static_cast<double>(ts), static_cast<std::string>(fmt));\n";
    out << "}\n\n";

    // --- json module runtime ---
    out << "inline std::string np_json_stringify(const np_var& val) {\n";
    out << "    if (std::holds_alternative<int64_t>(val.v)) {\n";
    out << "        return std::to_string(std::get<int64_t>(val.v));\n";
    out << "    }\n";
    out << "    if (std::holds_alternative<double>(val.v)) {\n";
    out << "        return std::to_string(std::get<double>(val.v));\n";
    out << "    }\n";
    out << "    if (std::holds_alternative<bool>(val.v)) {\n";
    out << "        return std::get<bool>(val.v) ? \"true\" : \"false\";\n";
    out << "    }\n";
    out << "    if (std::holds_alternative<np_string>(val.v)) {\n";
    out << "        std::string s = std::get<np_string>(val.v);\n";
    out << "        std::string res = \"\\\"\";\n";
    out << "        for (char c : s) {\n";
    out << "            if (c == '\"') res += \"\\\\\\\"\";\n";
    out << "            else if (c == '\\\\') res += \"\\\\\\\\\";\n";
    out << "            else if (c == '\\n') res += \"\\\\n\";\n";
    out << "            else if (c == '\\t') res += \"\\\\t\";\n";
    out << "            else if (c == '\\r') res += \"\\\\r\";\n";
    out << "            else res += c;\n";
    out << "        }\n";
    out << "        res += \"\\\"\";\n";
    out << "        return res;\n";
    out << "    }\n";
    out << "    if (std::holds_alternative<ListPtr>(val.v)) {\n";
    out << "        ListPtr ptr = std::get<ListPtr>(val.v);\n";
    out << "        if (!ptr) return \"[]\";\n";
    out << "        std::string res = \"[\";\n";
    out << "        for (size_t i = 0; i < ptr->vec.size(); ++i) {\n";
    out << "            res += np_json_stringify(ptr->vec[i]);\n";
    out << "            if (i < ptr->vec.size() - 1) res += \",\";\n";
    out << "        }\n";
    out << "        res += \"]\";\n";
    out << "        return res;\n";
    out << "    }\n";
    out << "    if (std::holds_alternative<DictPtr>(val.v)) {\n";
    out << "        DictPtr ptr = std::get<DictPtr>(val.v);\n";
    out << "        if (!ptr) return \"{}\";\n";
    out << "        std::string res = \"{\";\n";
    out << "        auto it = ptr->map.begin();\n";
    out << "        while (it != ptr->map.end()) {\n";
    out << "            res += \"\\\"\" + it->first + \"\\\":\" + np_json_stringify(it->second);\n";
    out << "            it++;\n";
    out << "            if (it != ptr->map.end()) res += \",\";\n";
    out << "        }\n";
    out << "        res += \"}\";\n";
    out << "        return res;\n";
    out << "    }\n";
    out << "    if (std::holds_alternative<np_int128>(val.v)) {\n";
    out << "        return std::get<np_int128>(val.v).to_string();\n";
    out << "    }\n";
    out << "    if (std::holds_alternative<np_int256>(val.v)) {\n";
    out << "        return std::get<np_int256>(val.v).to_string();\n";
    out << "    }\n";
    out << "    return \"null\";\n";
    out << "}\n";
    out << "struct np_json_parser_t {\n";
    out << "    std::string src;\n";
    out << "    size_t pos = 0;\n";
    out << "    void skip_whitespace() {\n";
    out << "        while (pos < src.size() && (src[pos] == ' ' || src[pos] == '\\t' || src[pos] == '\\n' || src[pos] == '\\r')) pos++;\n";
    out << "    }\n";
    out << "    char peek() {\n";
    out << "        skip_whitespace();\n";
    out << "        if (pos >= src.size()) return '\\0';\n";
    out << "        return src[pos];\n";
    out << "    }\n";
    out << "    char get() {\n";
    out << "        skip_whitespace();\n";
    out << "        if (pos >= src.size()) return '\\0';\n";
    out << "        return src[pos++];\n";
    out << "    }\n";
    out << "    np_var parse_value() {\n";
    out << "        char c = peek();\n";
    out << "        if (c == '{') return parse_object();\n";
    out << "        if (c == '[') return parse_array();\n";
    out << "        if (c == '\"') return parse_string();\n";
    out << "        if (c == 't' || c == 'f') return parse_bool();\n";
    out << "        if (c == 'n') { pos += 4; return np_var(); }\n";
    out << "        if ((c >= '0' && c <= '9') || c == '-') return parse_number();\n";
    out << "        return np_var();\n";
    out << "    }\n";
    out << "    np_var parse_object() {\n";
    out << "        get(); // '{'\n";
    out << "        std::map<std::string, np_var> obj;\n";
    out << "        if (peek() == '}') { get(); return np_var(obj); }\n";
    out << "        while (true) {\n";
    out << "            np_var key_var = parse_string();\n";
    out << "            std::string key = static_cast<std::string>(key_var);\n";
    out << "            if (get() != ':') return np_var(obj);\n";
    out << "            np_var val = parse_value();\n";
    out << "            obj[key] = val;\n";
    out << "            char c = peek();\n";
    out << "            if (c == '}') { get(); break; }\n";
    out << "            if (c == ',') get();\n";
    out << "            else break;\n";
    out << "        }\n";
    out << "        return np_var(obj);\n";
    out << "    }\n";
    out << "    np_var parse_array() {\n";
    out << "        get(); // '['\n";
    out << "        std::vector<np_var> arr;\n";
    out << "        if (peek() == ']') { get(); return np_var(arr); }\n";
    out << "        while (true) {\n";
    out << "            arr.push_back(parse_value());\n";
    out << "            char c = peek();\n";
    out << "            if (c == ']') { get(); break; }\n";
    out << "            if (c == ',') get();\n";
    out << "            else break;\n";
    out << "        }\n";
    out << "        return np_var(arr);\n";
    out << "    }\n";
    out << "    np_var parse_string() {\n";
    out << "        get(); // '\"'\n";
    out << "        std::string s = \"\";\n";
    out << "        while (pos < src.size()) {\n";
    out << "            char c = src[pos++];\n";
    out << "            if (c == '\"') break;\n";
    out << "            if (c == '\\\\' && pos < src.size()) {\n";
    out << "                char next = src[pos++];\n";
    out << "                if (next == '\"') s += '\"';\n";
    out << "                else if (next == '\\\\') s += '\\\\';\n";
    out << "                else if (next == 'n') s += '\\n';\n";
    out << "                else if (next == 't') s += '\\t';\n";
    out << "                else if (next == 'r') s += '\\r';\n";
    out << "                else s += next;\n";
    out << "            } else {\n";
    out << "                s += c;\n";
    out << "            }\n";
    out << "        }\n";
    out << "        return np_var(s);\n";
    out << "    }\n";
    out << "    np_var parse_bool() {\n";
    out << "        if (peek() == 't') { pos += 4; return np_var(true); }\n";
    out << "        else { pos += 5; return np_var(false); }\n";
    out << "        return np_var();\n";
    out << "    }\n";
    out << "    np_var parse_number() {\n";
    out << "        size_t start = pos;\n";
    out << "        bool is_double = false;\n";
    out << "        while (pos < src.size()) {\n";
    out << "            char c = src[pos];\n";
    out << "            if ((c >= '0' && c <= '9') || c == '-' || c == '+' || c == 'e' || c == 'E') pos++;\n";
    out << "            else if (c == '.') { is_double = true; pos++; }\n";
    out << "            else break;\n";
    out << "        }\n";
    out << "        std::string num_str = src.substr(start, pos - start);\n";
    out << "        if (is_double) {\n";
    out << "            try { return np_var(std::stod(num_str)); } catch(...) { return np_var(0.0); }\n";
    out << "        } else {\n";
    out << "            try { return np_var(static_cast<int64_t>(std::stoll(num_str))); } catch(...) { return np_var(static_cast<int64_t>(0)); }\n";
    out << "        }\n";
    out << "    }\n";
    out << "};\n";
    out << "inline np_var np_json_parse(const std::string& src) {\n";
    out << "    np_json_parser_t parser;\n";
    out << "    parser.src = src;\n";
    out << "    return parser.parse_value();\n";
    out << "}\n";
    out << "inline np_var np_json_parse(const np_var& src) {\n";
    out << "    return np_json_parse(static_cast<std::string>(src));\n";
    out << "}\n";
    out << "inline bool np_regex_match(const std::string& pattern, const std::string& text) {\n";
    out << "    try { std::regex re(pattern); return std::regex_match(text, re); } catch(...) { return false; }\n";
    out << "}\n";
    out << "inline bool np_regex_match(const np_var& pattern, const np_var& text) {\n";
    out << "    return np_regex_match(static_cast<std::string>(pattern), static_cast<std::string>(text));\n";
    out << "}\n";
    out << "inline std::string np_regex_find(const std::string& pattern, const std::string& text) {\n";
    out << "    try {\n";
    out << "        std::regex re(pattern); std::smatch m; \n";
    out << "        if (std::regex_search(text, m, re)) return m.str(0);\n";
    out << "    } catch(...) {}\n";
    out << "    return \"\";\n";
    out << "}\n";
    out << "inline std::string np_regex_find(const np_var& pattern, const np_var& text) {\n";
    out << "    return np_regex_find(static_cast<std::string>(pattern), static_cast<std::string>(text));\n";
    out << "}\n";
    out << "inline std::string np_regex_replace(const std::string& pattern, const std::string& repl, const std::string& text) {\n";
    out << "    try { std::regex re(pattern); return std::regex_replace(text, re, repl); } catch(...) { return text; }\n";
    out << "}\n";
    out << "inline std::string np_regex_replace(const np_var& pattern, const np_var& repl, const np_var& text) {\n";
    out << "    return np_regex_replace(static_cast<std::string>(pattern), static_cast<std::string>(repl), static_cast<std::string>(text));\n";
    out << "}\n\n";

    // Insert dynamic parsed code
    out << cpp_code << "\n";

    out.close();
}